---
- hosts: web
  become: true
  tasks:
    - name: stop apache
      service:
        name: apache2
        state: stopped
    - name: deploy static website
      copy:
        src: index.html
        dest: /var/www/html
